name: Release

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions: {}

jobs:
  release:
    if: github.head_ref == 'release' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0

      - name: Build and create Thunderstore package
        run: mise run build

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8
        with:
          subject-path: './build/*.zip'

      - name: Create Release
        run: knope release --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Thunderstore
        shell: bash
        run: |
          ZIP_FILE=$(ls ./build/*.zip | head -1)
          dotnet tcli publish --file "$ZIP_FILE"
        env:
          TCLI_AUTH_TOKEN: ${{ secrets.TCLI_AUTH_TOKEN }}
